### ISSUE TITLE
option to disable drag with middlemouseclick?

### ISSUE THREAD

**Issue by Zanzavar** [jsplumb/katavorio#43]
I would like in jsplumb to be able to disable dragging of elements with the middle mouse button, so that dragging works only with the left button. Would it be possible to have an additional option in katavorio for enabling disabling middle mouse drag, e.g.

k.draggable(someElement, {
    middleButtonCanDrag:true
});

Or if there is a better way to achieve this i'm all ears :)

**Comment by sporritt** [comment]
you can return false from the start event callback, which is given the mouse event as one of its parameters. so testing the button type in this method should give you what you need i think.

**Comment by Zanzavar** [comment]
Thanks for the quick response @sporritt . Unfortunately this doesn't seem to work for my case as  i would like to skip completely the .draggable functionality on middle mouse click (I have a pannable background and would like the user to activate only the background pan on middle click over a draggable element)

**Comment by sporritt** [comment]
i see, right.  i am tempted to suggest that in the event the start callback returns false, katavorio should not consume the event at all. but i think i'd be a bit concerned as to the effect on any existing software that uses jsplumb/katavorio.

**Comment by Zanzavar** [comment]
It's fine, i solved it by setting a check in the parent element for middle click to ignore mouse events from children. Thanks again for the help, you may close the issue.
