### ISSUE TITLE
Behaviour of "stop" Lifecycle Event changed

### ISSUE THREAD

**Issue by janober** [jsplumb/katavorio#45]
Hi,
did just spend a lot of time wondering why my code does not work anymore till I realized that the reason was that npm updated jsplumb from 2.7.9 -> 2.8.8 which should normally not break anything. But with that upgrade is now also uses katavorio 1.2.0 instead of 0.9.1 which probably broke stuff after all. 
Because before when multiple nodes were in a "DragSelection" it emitted not just multiple "start" and "drag" events (which is still does") it also did emit multiple "stop" ones. That, however, is not the case anymore.

Here the jsfiddles:

jsplumb@2.7.19 & katavorio@0.9.1:
https://jsfiddle.net/u139hytL/3/
Does get correctly emitted 3x

jsplumb@2.8.8 & katavorio@1.2.0:
https://jsfiddle.net/u139hytL/2/
Does just get emitted 1x

Anybody any idea? Thanks!

**Comment by sporritt** [comment]
the object passed to the `stop` event callback has a `selection` array in it, which contains the id and new position of all elements that have moved.

**Comment by janober** [comment]
First thanks a lot for the very fast answer!
Sorry I did probably not really bring the point across what my problem is. I do not have a problem getting it to work with the new behavior. It is already working fine again (even though my code is now much more complicated and ugly). The problem I have is that it is a breaking change and breaking changes should not happen in a minor version upgrade. And now looking into that some more it seems it even must have broken from 2.8.0 to 2.8.1 which is only a bugfix version change where really really no breaking changes should happen. And if there is no way around a breaking change and for some reason, a major version upgrade is not possible at very least I would expect very clearly stated somewhere that feature X will work differently now (but then also only in a minor and never a bugfix version).
Please do not understand me wrong. Jsplumb and katavorio are really great projects and I am incredibly glad that they are there. They normally also work perfectly fine. But for me (and I am also sure other people) it is important to know that code does not simply break. I, for example, was for hours sure that I must have broke something as I knew I did not make any changes to the jsplumb version in months. It did not even cross my mind for that time that such a crucial behavior would knowingly change.

**Comment by janober** [comment]
I would say it is a common pattern to not set a specific version for every package. Especially for bugfix (patch) versions. As they normally supposed to never break anything and just fix bugs. Even more when in active development phase like I am right now (one of the reasons why I thought I was the problem). Sure for production-setups that is something totally else but also there it depends a lot on the application and the size of the company and so at least the bugfix version does not always have to be fixed.

And it is not really of the size of the change it is simply about if it breaks stuff or not. Here is the official npm-page about that: https://docs.npmjs.com/about-semantic-versioning
There it states for both patch & minor clearly backward compatibility. And that is exactly what people expect from npm packages.

So would be great to know that at least bugfix versions are always backward compatible in the future. And if breaking changes occur that they are clearly documented somewhere. Think especially for an Open Source project that is very important. 

Why it is more complex: The reason is that I use it with Vue and I have a node-component (for each draggable) where each node simply takes care of itself. Which was easy because each dragged node got their own "stop" event and so could easily do that. Now not so nice anymore as only one node gets the "stop" event for all of them and so also has to take care of other nodes.

**Comment by sporritt** [comment]
the notion that it's a common pattern to not set a specific version for every package doesn't have any bearing on my opinion on whether or not it's a good idea. i am also not swayed by what someone at npm wrote on their "official page". it simply isn't a good idea to leave dependencies up to the vagaries of the universe.  it's irresponsible. 

shall i close this then? your app is working?

**Comment by sporritt** [comment]
i don't think i'll be able to reinstate the original stop callback behaviour. but i will switch to strict semantic versioning for the Community edition of jsplumb and its associated projects.

**Comment by sporritt** [comment]
you know, after thinking about this a while, i don't think I will in fact be switching to strict semantic versioning. i don't agree with it, specifically with the limitation that breaking API changes must result in bumping the major version.
